### ISSUE TITLE
-passthru and other options broken

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/jtrTestSuite#61]
```
$ ./jtrts.pl -passthru="--fork=3"
Can't use string ("--fork=3") as an ARRAY ref while "strict refs" in use at ./jtrts.pl line 150.
```

```
$ ./jtrts.pl -type sapb
Can't use string ("sapb") as an ARRAY ref while "strict refs" in use at ./jtrts.pl line 147.
```

This makes the warning go away:
```
$ git diff
diff --git a/jtrts.pl b/jtrts.pl
index 9513ac1..a3556b9 100755
--- a/jtrts.pl
+++ b/jtrts.pl
@@ -1,5 +1,5 @@
 #!/usr/bin/perl -w
-use strict;
+#use strict;
 use Getopt::Long;
 use jtrts_inc;
 use Digest::MD5;
```
But then, the -type and -passthru options are just ignored.

According to `git bisect`, commit 2847802fede15ca75f51debf070fd18c7295cabe (adding -resume) caused this problem.

**Comment by magnumripper** [comment]
I reported that in #59 a while ago.

**Comment by jfoug** [comment]
Fixed here ced2309 .  Not sure why it could not handle it in strict mode, but the work around is trivial, and things 'seem' to work (i.e. I think Passthru is still functional, AND resume pulls passthru back).

**Comment by frank-dittrich** [comment]
@jfoug this doesn't fix it.

1. I tried disabling "strict" (by just commenting out that line).
That removed the warning, but caused the option to be ignored.

Your "fix" is similar.
Otherwise this shouldn't work, but fail:
```
$ ./jtrts.pl -passthru="--xxxxxxxxxx"
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1117-gb39547a [linux-gnu 64-bit AVX-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=dynamic_0                    guesses: 1502 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_0                guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)

form=dynamic_0                    guesses:  920 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_0                guesses:  920 0:00:00:00 DONE  [PASSED] (920 val-pwd)

```

```
$ ./jtrts.pl -passthru="--fork=0"
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1117-gb39547a [linux-gnu 64-bit AVX-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=dynamic_0                    guesses: 1502 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_0                guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)

form=dynamic_0                    guesses:  920 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_0                guesses:  920 0:00:00:00 DONE  [PASSED] (920 val-pwd)

```

```
$ ./jtrts.pl -passthru="--node=1/2"
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1117-gb39547a [linux-gnu 64-bit AVX-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=dynamic_0                    guesses: 1502 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_0                guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)

form=dynamic_0                    guesses:  920 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_0                guesses:  920 0:00:00:00 DONE  [PASSED] (920 val-pwd)

```

2. You ignored the "and other commands" int the title.

Example: -type not working:
```
$ ./jtrts.pl -type sapb
Can't use string ("sapb") as an ARRAY ref while "strict refs" in use at ./jtrts.pl line 147.
```

**Comment by jfoug** [comment]
Grr,  I will have to dig in deeper, and find the solution.....  I may have to pull this out of the opts, and handle it by itself, if I can not find any other solution.

**Comment by jfoug** [comment]
@frank-dittrich please test now. I 'think' this has it licked.  I have tested using -max-run-time (which needed an adjustment made to the show_pass reduction section).  It is certainly passing the data into john to use now.

I found the other code to move from hash into array on the net.  It seems to not work at all (but would compile).  As soon as one of the hash elements was defined, it would do the assignment and fail.  I 'think' things are working.   NOTE, the ARGV original code was left, because I am not sure that it did not work before, so I left that 'method' but commented it out.I will be doing more testing, making sure that resume IS working properly, etc, but I think things are now right.

**Comment by magnumripper** [comment]
I need to look at this code when I get the time. I thought I knew perl pretty well but this problem had me totally stumped.

**Comment by frank-dittrich** [comment]
I think this is fixed now.

**Comment by jfoug** [comment]
The ``` @VAR              = @{$opts{var}}; ``` syntax, I found on the web. Once I got it to that syntax, errors went away, and it compiled / ran, and was resuming, so I thought things were right.

However, it was NOT right at all.  It was trying to do this:   ``` @VAR = @{"some string"}; ```  So what I did was simply split the string on white space. So now it is ```@VAR = split /\s+/, "some string"; ```which I 'know'  works just fine for building an array.

**Comment by magnumripper** [comment]
> So if there are 3 different switched, you will have to do: -pass-thru='-switch1=yes switch2=no switch3=what' same thing if you use the -type switch (I usually do not). They need to be space padded.

That's what I would have figured anyway so it's definitely not a regression. Good stuff. I'm still not very keen on that json shit but that's because I'm older than your dog and hate everything that happened since 1985 :sunglasses:

**Comment by jfoug** [comment]
Well my dog is only 9, so you damn well better be older than that.    I would be somewhat shocked, if I did not have you be a few years, but I certainly could be wrong, since the INet is a good place to hide behind.

JSON, is damn nice.  Very simple, descriptive language.  Much simpler than XML, but pretty much as powerful.  The way I am using it is pretty  trivial.  Just token=value ; type stuff, like would be in most configuration files.   But why write config from the ground up, when something like JSON already has it easily, and with the perl mods, you do not even have to write code.  The entire code is only a few lines long in the TS  (a write function and a read function).

**Comment by magnumripper** [comment]
Nine years is 63 dog years :dog2: but actually I'm younger than that :sunglasses: 

I don't mind JSON as much as I mind the dependency of the lib. On the openwall hosts (I forgot which, maybe one, maybe all of them) I couldn't even install it as a user. I probably just did it wrong.

**Comment by jfoug** [comment]
You can (should be able to) install it locally.  I have had to do that often on some of our work servers, to figure out exactly which items required install, then get the unix team to actually later install pods as root.  But installed locally works fine.   We had some hard to build stuff (some of the DBI oracle stuff).  Took a bit to get things right, and I had to do it local, and get a 'working' procedure for them.  Once we got the libs and other requirements figured out, it was cake ;)  I thought JSON::XS was easy.  Had very few dependencies.

A 9 yr old small/medium dog is actually between 52 and 60 (using online calcs). I have always gone with 1 year for first year, then 7 per after that (for smaller sized dogs).  I would consider her 57, and yes, she is getting to be an old grumpy bitch.

**Comment by magnumripper** [comment]
> You can (should be able to) install it locally.

Yeah excepts it fails self-test on all occasions I tried it (different machines). There are a huge amount a pure crap on CPAN and the problem is you don't know which is good and which is written by a five year old.

Perhaps we need to change to some better module.

**Comment by jfoug** [comment]
hmm,  I had a really easy time with it.  Was it dependencies that did not load or what?  Damn, JSON parsing is so trivia, I would think a 5yr old would be  able to get it right, lol.

**Comment by magnumripper** [comment]
On super there was a wall of text and then it ended like this
```
Result: FAIL
Failed 10/25 test programs. 0/24771 subtests failed.
make: *** [test_dynamic] Error 255
  MLEHMANN/JSON-XS-3.01.tar.gz
  /usr/bin/make test -- NOT OK
```
I could use 'force' to install it anyway but that doesn't feel right when dealing with *our* test suite, lol.
